### ISSUE TITLE
How to avoid automatic .tex extension in filenames?

### ISSUE THREAD

**Issue by faridcher** [mavam/stat-cookbook#15]
When I am going to build the pdf in Window 7 using MikteX I get the error:
`! LaTeX Error: File 'VERSION.tex' not found.`

[This bug](https://sourceforge.net/p/miktex/bugs/1248/) is already reported to MikteX team, yet it is not fixed. According to the following thread at SE the workaround would be to add a dot after the file name:
`\newcommand{\version}{\input{VERSION.}}`
[read-file-without-file-extension-from-hidden-directory](http://tex.stackexchange.com/questions/128323/read-file-without-file-extension-from-hidden-directory)

If we add this dot, would the tex file be compiled within your platform (e.g. linux)?
Thanks

**Comment by mavam** [comment]
> If we add this dot, would the tex file be compiled within your platform (e.g. linux)?

Adding a trailing dot didn't work for me; I get a compile error on OSX. I've now embedded the version in the LaTeX document directly.
