### ISSUE TITLE
Few misprints

### ISSUE THREAD

**Issue by allipatev** [mavam/stat-cookbook#18]
Dear Matthias Vallentin!
Your cookbook is great and almost exhaustive.
But could you please re-check the following in the _4 Expectation_ section:

1) The formula EX=sum(P{X>=x}) is right only for integer-valued RVs. Probably it should be mentioned explicitly.
2) The last formula in _Conditional expectation_ probably needs another parentheses configuration.

**Comment by mavam** [comment]
Thanks for the report, I've incorporated your suggestions and just released [version 0.2.3](https://github.com/mavam/stat-cookbook/releases/tag/0.2.3).
