### ISSUE TITLE
Expectation: typo in equation

### ISSUE THREAD

**Issue by alphaville** [mavam/stat-cookbook#19]
On page 9 it is written that two variables have the same expectation (E[X] = E[Y]) if and only if they are almost surely equal (P[X=Y]=1). However, we may have two random variables X, Y which have the same expectation, even the same distribution, but are almost surely not equal - take X~N(0,1) and Y=-X.

I believe you meant to write P[X=Y] = 1 => E[X] = E[Y].

**Comment by mavam** [comment]
Thanks for submitting the issue. This is indeed a typo and I'll fix it on the next occasion.
