### ISSUE TITLE
Wrong Negative Binomial MGF

### ISSUE THREAD

**Issue by Achab94** [mavam/stat-cookbook#29]
Hi,
The moment generating function of a Negative Binomial distribution is wrong (see 1.1 Discrete Distribution tables).
It should be the MGF of a Geometric distribution (which is indeed correct), raised to the r-th power. 

**Incorrect version**:
<img src="https://render.githubusercontent.com/render/math?math=\left(\frac{p}{1-(1-p)e^s} \right)^r">

**Corrected version**:
<img src="https://render.githubusercontent.com/render/math?math=\left(\frac{p e^s}{1-(1-p)e^s} \right)^r">

Cheers :)

**Comment by mavam** [comment]
Correct! Thanks for the bug report and sorry that it took me so long to fix it.
