### ISSUE TITLE
Book suggestion

### ISSUE THREAD

**Issue by balaji-ch** [mavam/stat-cookbook#30]
Hi Matthias ,
Thanks for the cookbook. Can you suggest a good book for Probability and statistics ?

**Comment by mavam** [comment]
I can only second @ivanistheone's comment regarding *All of Statistics*. It's a classic. It can be too intense and minimalistic, but it's perfect foundational literature when taking a course in statistics, as it really nails the individual concepts.

When trying things out with R, I would make sure that you don't invest too much time. While it's nice to try things out, there are more modern frameworks and packages out there (e.g., tidyverse) with a superior UX.

**Comment by balaji-ch** [comment]
> There are a bunch of books for beginners, but they don't explain things well at all.

_There are a bunch of books for beginners, but they don't explain things well at all._ 

Classic problem.
Thanks for suggesting good refs.
