### ISSUE TITLE
build issue with translator

### ISSUE THREAD

**Issue by jarrodmillman** [mavam/stat-cookbook#6]
It looks like translator is coming from beamer:

```
(/usr/share/texlive/texmf-dist/tex/latex/beamer/translator/translator.sty
Package: translator 2010/06/12 ver 1.10

(/usr/share/texlive/texmf-dist/tex/latex/beamer/translator/translator-language-
mappings.tex)) (/usr/share/texlive/texmf-dist/tex/latex/tools/xspace.sty
Package: xspace 2009/10/20 v1.13 Space after command names (DPC,MH)
)
```

Instead of providing the default english translation when I execute:

$ make
or 
$ make en

I get the warnings like:
```
Package hyperref Warning: Token not allowed in a PDF string (PDFDocEncoding):
(hyperref)                removing `\translate ' on input line 111.
```

I will look into it further later, but wanted to record the issue here.  If you see an obvious fix, great.  If not, I will look into it further over the winter break.

**Comment by mavam** [comment]
In the future, I plan to complete remove translation support inside the repository and switch back to English inside the main LaTeX file. After having had this support for a couple of years in place, it did not receive a single translated version. The per-phrase granularity is not only too strict, but also cumbersome to work with. Instead, when someone wants to maintain a translation, they should send me the link to their fork and I'll add it to the README, as in https://github.com/agis-/git-style-guide.
